### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'info.txt' 

### ISSUE THREAD

**Issue by sishui8000** [sharmapn/MapSafe-QGIS-plugin#3]
Hello, I encountered an issue when encrypting the map. It shows a permission denied error. I followed the configuration steps in your official documentation. Is there any specific environment setting that needs to be modified?
![QQ截图20241212113759](https://github.com/user-attachments/assets/6a88e6e5-6b13-4f02-b551-22e8d2cbaf87)

**Comment by sharmapn** [comment]
Thank you for informing me. I am looking into this now.

**Comment by sharmapn** [comment]
Hello,

I tried to encrypt the three different datasets from the datasets folder and it works fine. Please see below. 

The issue may arise from trying to encrypt the same file at all three levels. I will add code to handle this scenario.

![image](https://github.com/user-attachments/assets/b452811f-a600-456d-82c4-9ff59e26a05b)

**Comment by sishui8000** [comment]
![image](https://github.com/user-attachments/assets/295c1bb2-98a0-489e-913e-b0c5099d1d47)
![image](https://github.com/user-attachments/assets/c865bb31-c3ac-454d-9502-af8ae7f40960)

I tried encrypting three files, but the error still persists. I also tested different generate passphrase options, but the issue remains the same. Is there anything else I should check or adjust?


Here are the logs:

# Python Console
# Use iface to access QGIS API interface or type '?' for more info
# Security warning: typing commands from an untrusted source can harm your computer
Working Directory Set: True
		----------------------------------------------------------
		self.passphrase: upstate proxy galore grandma yearly arrival fantasy prowling dares earflap flirt vitalize those proposal unmanned
		self.levels_to_encrypt: 3
		self.filename1: C:/datasets/test1.gpkg
		self.filename2: C:/datasets/test2.gpkg
		self.filename3: C:/datasets/test.zip
		self.label_passphrase_loc: <PyQt5.QtWidgets.QLabel object at 0x000001BB02505C70>
		----------------------------------------------------------
chosen_filename_level1: C:/datasets/test1.gpkg
passphrase passed: upstate proxy galore grandma yearly arrival fantasy prowling dares earflap flirt vitalize those proposal unmanned
Working directory set: C:\datasets
self.working_di: C:\datasets
start: 1733996394.8242946
#### Encrypting Level 1 - Inner Level
file_name: test1.gpkg

**Comment by sharmapn** [comment]
Hello,
Could you try renaming the files so that all of them do no have the term ‘test’ in the file name?

also check if you or QGIS has permissions on that folder.

just try encrypting one level, if that works then try two levels and then try three levels.

let me know how it goes.

**Comment by sishui8000** [comment]
Of course, I’ve already tried using different names. I didn’t see any option to modify the encryption level because the error message pops up immediately when I click to encrypt. I also suspect it might be a permissions issue, but I noticed that my plugin’s installation directory is almost identical to yours. Additionally, I tried changing the folder permissions to make it writable, but it didn’t help.
I also tried modifying the info.txt file, but that didn’t work either.I tried using different plugin installation methods, such as installing directly from a ZIP file.

**Comment by sharmapn** [comment]
Hi,
The encryption is working on my text machine. You can try these steps.
Reload the MapSafe plugin using the 'Plugin Reloader' plugin.
Then change the Combined mode to the Individual mode. 
Then proceed directly to encryption and encrypt only one file - at level one. Does encrypt work? If not let me know.
If it does then proceed to encryption of two files - at level 1 and level 2. Does encrypt work? If not let me know.
If it does then proceed to encryption of three files - at level 1 and level 2 and level 3. Does encrypt work? If not let me know.

**Comment by sishui8000** [comment]
Oh, I finally managed to make it work! Here are the steps I followed:

I used the ZIP file downloaded via Git and installed it directly in QGIS instead of using the plugin marketplace. I had also tried the Plugin Reloader from the marketplace, but it didn’t work.
I went to the plugin installation directory and removed the "read-only" attribute for the entire folder.
I opened QGIS with administrator privileges.
I’m not sure which of these steps was the most effective, but I suspect it might be a combination of them since I had tried most of them individually without success. I hope this helps you!

**Comment by sharmapn** [comment]
Oh, Thank you so much. 
I hope this helps others facing this permission problem.

**Comment by sharmapn** [comment]
Based on the provided solution, I am closing thus issue.

**Comment by sharmapn** [comment]
Hi @sishui8000, 
Could you please carry out a Heuristic Evaluation for the plugin? It has 10 questions and should not take more than 10  minutes. Workbook (PDF) to this email. https://media.nngroup.com/media/articles/attachments/Heuristic_Evaluation_Workbook_1_Fillable.pdf

Please download the newest version of the plugin I uploaded this week.

This evaluation is a bit time-sensitive, as we need it for our upcoming paper. We’d really appreciate it if you could prioritize this task.

Thank you so much for your help!

Best regards,
Pankaj
